import type { Project } from "./types"

export const projects: Project[] = [
  {
    id: "p1",
    title: "City Rush",
    slug: "city-rush",
    cover: "/posters/city-rush.jpg",
    year: 2024,
    durationSec: 30,
    tags: ["Commercial"],
    client: "Athletic Brand",
    role: ["Editor", "Color"],
    createdAt: "2024-08-01T12:00:00Z",
  },
  {
    id: "p2",
    title: "Afterglow",
    slug: "afterglow",
    cover: "/posters/afterglow.jpg",
    year: 2023,
    durationSec: 540,
    tags: ["Narrative", "Color"],
    client: "Indie",
    role: ["Editor"],
    createdAt: "2023-05-10T12:00:00Z",
  },
  {
    id: "p3",
    title: "Pulse",
    slug: "pulse",
    cover: "/posters/pulse.jpg",
    year: 2024,
    durationSec: 210,
    tags: ["Music Video", "Motion"],
    client: "Artist",
    role: ["Editor", "Motion"],
    createdAt: "2024-01-15T12:00:00Z",
  },
  {
    id: "p4",
    title: "Nebula",
    slug: "nebula",
    cover: "/posters/nebula.jpg",
    year: 2022,
    durationSec: 45,
    tags: ["VFX", "Short-form"],
    role: ["Editor", "VFX"],
    createdAt: "2022-11-20T12:00:00Z",
  },
  {
    id: "p5",
    title: "Horizon",
    slug: "horizon",
    cover: "/posters/horizon.jpg",
    year: 2021,
    durationSec: 120,
    tags: ["Commercial", "Color"],
    client: "Brand Film",
    role: ["Color"],
    createdAt: "2021-07-01T12:00:00Z",
  },
  {
    id: "p6",
    title: "Echoes",
    slug: "echoes",
    cover: "/posters/echoes.jpg",
    year: 2020,
    durationSec: 600,
    tags: ["Narrative"],
    client: "Festival",
    role: ["Editor"],
    createdAt: "2020-02-14T12:00:00Z",
  },
  {
    id: "p7",
    title: "Velocity",
    slug: "velocity",
    cover: "/posters/velocity.jpg",
    year: 2024,
    durationSec: 20,
    tags: ["Short-form", "Motion"],
    createdAt: "2024-09-10T12:00:00Z",
  },
  {
    id: "p8",
    title: "Studio Noir",
    slug: "studio-noir",
    cover: "/posters/studio-noir.jpg",
    year: 2023,
    durationSec: 60,
    tags: ["Commercial", "VFX"],
    createdAt: "2023-09-01T12:00:00Z",
  },
]

export const TAGS = [
  "All",
  "Commercial",
  "Narrative",
  "Music Video",
  "VFX",
  "Color",
  "Motion",
  "Short-form",
] as const

